name: antigravity_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  workmanager: ^0.9.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
